defaults:
  - model
  - _self_

name: 'Tiger14n/ropewhisper-tiny'
input_features: true
project_encoder_input: false

do_style_embed: false
do_difficulty_embed: true
do_mapper_embed: true
do_song_position_embed: true
cond_dim: 128
cond_size: 384

spectrogram:
  implementation: 'torchaudio'
  log_scale: true
  n_mels: 80
  f_min: 20
  pad_mode: 'reflect'

overwrite:
  tie_word_embeddings: false